# Generated by Django 4.2.11 on 2024-04-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_id', models.CharField(max_length=255, unique=True)),
                ('patient_id', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('hn_number', models.CharField(default='00000', max_length=5, null=True, unique=True)),
                ('bed_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('temp', models.CharField(blank=True, max_length=255)),
                ('pulse', models.CharField(blank=True, max_length=255)),
                ('respirations', models.CharField(blank=True, max_length=255)),
                ('bp_systolic', models.CharField(blank=True, max_length=255)),
                ('bp_diastolic', models.CharField(blank=True, max_length=255)),
                ('map', models.CharField(blank=True, max_length=255)),
                ('o2_sat', models.CharField(blank=True, max_length=255)),
                ('pain_score', models.CharField(blank=True, max_length=255)),
                ('height_of_fundus', models.CharField(blank=True, max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255)),
                ('hight', models.CharField(blank=True, max_length=255)),
                ('diet', models.CharField(blank=True, max_length=255)),
                ('urination', models.CharField(blank=True, max_length=255)),
                ('defecations', models.CharField(blank=True, max_length=255)),
                ('intake_oral', models.CharField(blank=True, max_length=255)),
                ('intake_parenteral', models.CharField(blank=True, max_length=255)),
                ('intake_total', models.CharField(blank=True, max_length=255)),
                ('output_urine', models.CharField(blank=True, max_length=255)),
                ('output_emesis', models.CharField(blank=True, max_length=255)),
                ('output_total', models.CharField(blank=True, max_length=255)),
                ('total_intake', models.CharField(blank=True, max_length=255)),
                ('total_output', models.CharField(blank=True, max_length=255)),
                ('lochia', models.CharField(blank=True, max_length=255)),
                ('phlebitis', models.CharField(blank=True, max_length=255)),
                ('mews', models.CharField(blank=True, max_length=255)),
                ('pps', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('atb', models.CharField(blank=True, max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('measurement_time', models.DateTimeField(null=True)),
                ('operator_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bed_list', models.ManyToManyField(null=True, to='patient.stringitem')),
            ],
        ),
    ]
