# Generated by Django 4.2.11 on 2024-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_operatoruser_delete_customuser_delete_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='bed_list',
            field=models.ManyToManyField(null=True, to='patient.bed'),
        ),
    ]
