# Generated by Django 4.2.11 on 2024-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_ward_bed_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
