# Generated by Django 4.2.11 on 2024-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_ward_bed_list_ward_bed_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='bed_list',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
