# Generated by Django 4.2.11 on 2024-05-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_card',
            field=models.CharField(default='', max_length=13),
        ),
    ]
