# Generated by Django 4.2.11 on 2024-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_patient_bed_id_alter_patient_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_card',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
    ]
